# Form implementation generated from reading ui file 'Menu.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(803, 603)
        MainWindow.setStyleSheet("\n"
"background-color: rgb(214, 244, 244);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(280, 190, 221, 32))
        self.pushButton_2.setStyleSheet("background-color: rgb(255, 255, 255);color: rgb(15, 6, 9);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(280, 310, 221, 32))
        self.pushButton_3.setStyleSheet("background-color: rgb(255, 255, 255);color: rgb(15, 6, 9);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(280, 370, 221, 32))
        self.pushButton_4.setStyleSheet("background-color: rgb(255, 255, 255);color: rgb(15, 6, 9);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(280, 130, 221, 32))
        self.pushButton_5.setStyleSheet("background-color: rgb(255, 255, 255);color: rgb(15, 6, 9);")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(280, 250, 221, 32))
        self.pushButton_6.setStyleSheet("background-color: rgb(255, 255, 255);color: rgb(15, 6, 9);")
        self.pushButton_6.setObjectName("pushButton_6")
        self.textEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(350, 60, 81, 41))
        self.textEdit.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.textEdit.setObjectName("textEdit")
        self.pushButton_7 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(280, 470, 221, 32))
        self.pushButton_7.setStyleSheet("background-color: rgb(255, 255, 255);color: rgb(15, 6, 9);")
        self.pushButton_7.setObjectName("pushButton_7")
        self.toolButton = QtWidgets.QToolButton(parent=self.centralwidget)
        self.toolButton.setGeometry(QtCore.QRect(750, 550, 26, 22))
        self.toolButton.setStyleSheet("background-color: rgb(255, 255, 255);color: rgb(15, 6, 9);")
        self.toolButton.setObjectName("toolButton")
        self.pushButton_8 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(280, 420, 221, 32))
        self.pushButton_8.setStyleSheet("background-color: rgb(255, 255, 255);color: rgb(15, 6, 9);")
        self.pushButton_8.setObjectName("pushButton_8")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_2.setText(_translate("MainWindow", "Obtain patient information"))
        self.pushButton_3.setText(_translate("MainWindow", "Register new patient"))
        self.pushButton_4.setText(_translate("MainWindow", "Enter patient data"))
        self.pushButton_5.setText(_translate("MainWindow", "Calender"))
        self.pushButton_6.setText(_translate("MainWindow", "Book Consultation"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt; font-weight:600; color:#133493;\">Menu</span></p></body></html>"))
        self.pushButton_7.setText(_translate("MainWindow", "Settings"))
        self.toolButton.setText(_translate("MainWindow", "..."))
        self.pushButton_8.setText(_translate("MainWindow", "Inbox"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
