# Form implementation generated from reading ui file 'Indregistrering.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import mysql.connector

db = mysql.connector.connect(
    user='root',
    password='kaka9699',
    host='127.0.0.1',
    database='iteration3'
)

class Ui_RegisterWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 607)
        MainWindow.setStyleSheet("background-color: rgb(214, 244, 244);")

        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.textEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(240, 40, 341, 41))
        self.textEdit.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.textEdit.setObjectName("textEdit")

        self.textEdit_2 = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(240, 260, 141, 31))
        self.textEdit_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textEdit_2.setObjectName("textEdit_2")

        self.textEdit_3 = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.textEdit_3.setGeometry(QtCore.QRect(240, 440, 141, 41))
        self.textEdit_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textEdit_3.setObjectName("textEdit_3")

        self.textEdit_4 = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.textEdit_4.setGeometry(QtCore.QRect(240, 380, 141, 31))
        self.textEdit_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textEdit_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.textEdit_4.setObjectName("textEdit_4")

        self.cpr = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.cpr.setGeometry(QtCore.QRect(440, 260, 141, 31))
        self.cpr.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(10, 8, 17);")
        self.cpr.setObjectName("cpr")

        self.Weight = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.Weight.setGeometry(QtCore.QRect(440, 380, 141, 31))
        self.Weight.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Weight.setObjectName("Weight")

        self.textEdit_7 = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.textEdit_7.setGeometry(QtCore.QRect(240, 320, 141, 31))
        self.textEdit_7.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textEdit_7.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.textEdit_7.setObjectName("textEdit_7")

        self.Partner = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.Partner.setGeometry(QtCore.QRect(440, 320, 141, 31))
        self.Partner.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Partner.setObjectName("Partner")

        self.Pos_test_date = QtWidgets.QDateEdit(parent=self.centralwidget)
        self.Pos_test_date.setGeometry(QtCore.QRect(440, 440, 161, 41))
        self.Pos_test_date.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Pos_test_date.setObjectName("Pos_test_date")

        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(330, 520, 161, 32))
        self.pushButton.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton.setObjectName("pushButton")

        self.textEdit_11 = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.textEdit_11.setGeometry(QtCore.QRect(240, 200, 141, 31))
        self.textEdit_11.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textEdit_11.setObjectName("textEdit_11")

        self.textEdit_12 = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.textEdit_12.setGeometry(QtCore.QRect(240, 140, 141, 31))
        self.textEdit_12.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textEdit_12.setObjectName("textEdit_12")

        self.Last_name = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.Last_name.setGeometry(QtCore.QRect(440, 200, 141, 31))
        self.Last_name.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(10, 8, 17);")
        self.Last_name.setObjectName("Last_name")

        self.First_name = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.First_name.setGeometry(QtCore.QRect(440, 140, 141, 31))
        self.First_name.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(10, 8, 17);")
        self.First_name.setObjectName("First_name")

        MainWindow.setCentralWidget(self.centralwidget)

        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.cpr_error = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.cpr_error.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.cpr_error.setStyleSheet("color: rgb(214, 244, 244);")
        self.cpr_error.setGeometry(QtCore.QRect(600, 260, 141, 50))

        self.partner_error = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.partner_error.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.partner_error.setStyleSheet("color: rgb(214, 244, 244);")
        self.partner_error.setGeometry(QtCore.QRect(600, 320, 141, 50))

        self.weight_error = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.weight_error.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.weight_error.setStyleSheet("color: rgb(214, 244, 244);")
        self.weight_error.setGeometry(QtCore.QRect(600, 380, 141, 60))

        self.firstname_error = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.firstname_error.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.firstname_error.setStyleSheet("color: rgb(214, 244, 244);")
        self.firstname_error.setGeometry(QtCore.QRect(600, 140, 141, 50))

        self.lastname_error = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.lastname_error.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.lastname_error.setStyleSheet("color: rgb(214, 244, 244);")
        self.lastname_error.setGeometry(QtCore.QRect(600, 200, 141, 50))

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.pushButton.clicked.connect(self.click_button)

# A function that defines the inputboxes and decides if the information put in is correct once the pushbuttom is pressed.
# First of all the textEdit boxes that we use are defined, so the names are easier.
    def click_button(self):
        ''' We use toPlainText to contain the plain text in the text edit'''
        cpr_input = self.cpr.toPlainText()
        weight_input = self.Weight.toPlainText()
        partner_input = self.Partner.toPlainText()
        firstname_input = self.First_name.toPlainText()
        lastname_input = self.Last_name.toPlainText()
        # The first condition states, that the input should be numbers and that it should consist of exactly 10 numbers.
        condition1 = cpr_input.isdigit() and len(str(cpr_input)) == 10
        # The second condition states, that the input should be letters, and that the text3 box shall accept either, Yes, yes, No or no.
        condition2 = partner_input.isalpha() and (partner_input == 'Yes' or partner_input == 'No' or partner_input == 'yes' or partner_input == 'no')
        # Condition 3 states that the number should be numbers between 30 and 200, and that it can be a decimalnumber
        condition3 = 30.00 < float(weight_input) < 200.00
        # Condition 4 states that the first name must be letters
        condition4 = firstname_input.isalpha()
        # Condition 5 states that the last name also must be letters
        condition5 = lastname_input.isalpha()

        # We make an if statement that makes the program say "Registration complete" when all three conditions are fulfilled
        # and that the program should tell which input is not correct if the conditions is not fulfilled.
        if condition1 and condition2 and condition3 and condition4 and condition5:
            print('Registration Complete')
            self.pushButton.setText("Registration Complete")
            self.pushButton.setStyleSheet("background-color: rgb(0, 255, 0)")
            cursor = db.cursor()
            insert_patient = (
                "INSERT INTO Patient (CPR, Firstname, Lastname, Address, birthDate, `Assigned Healthcare Worker`, MaritalStatus, Weight, Height) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)"
            )
            if partner_input == 'Yes' or partner_input == 'yes':
                values = (cpr_input, firstname_input, lastname_input, None, None, None, "married", weight_input, None)
            else:
                values = (cpr_input, firstname_input, lastname_input, None, None, None, "single", weight_input, None)
            cursor.execute(insert_patient,values)
            db.commit()
            print("Stored successfully")
        elif condition1 == False:
            print('The entered CPR-number is invalid')
            self.pushButton.setText("Registration not complete")
            self.pushButton.setStyleSheet("background-color: rgb(255, 0, 0)")
            self.cpr_error.setGeometry(QtCore.QRect(600, 260, 141, 50))
            self.cpr_error.setStyleSheet("color: rgb(255, 0, 0)")
        elif condition2 == False:
            print('Response should be either "Yes" or "No"')
            self.pushButton.setText("Registration not complete")
            self.pushButton.setStyleSheet("background-color: rgb(255, 0, 0)")
            self.partner_error.setGeometry(QtCore.QRect(600, 320, 141, 50))
            self.partner_error.setStyleSheet("color: rgb(255, 0, 0)")
        elif condition3 == False:
            print('Weight is not between 30 and 200 kilograms')
            self.pushButton.setText("Registration not complete")
            self.pushButton.setStyleSheet("background-color: rgb(255, 0, 0)")
            self.weight_error.setGeometry(QtCore.QRect(600, 380, 141, 60))
            self.weight_error.setStyleSheet("color: rgb(255, 0, 0)")
        elif condition4 == False:
            print('First name must be letters')
            self.pushButton.setText("Registration not complete")
            self.pushButton.setStyleSheet("background-color: rgb(255, 0, 0)")
            self.firstname_error.setGeometry(QtCore.QRect(600, 140, 141, 50))
            self.firstname_error.setStyleSheet("color: rgb(255, 0, 0)")
        elif condition5 == False:
            print('Last name must be letters')
            self.pushButton.setText("Registration not complete")
            self.pushButton.setStyleSheet("background-color: rgb(255, 0, 0)")
            self.lastname_error.setGeometry(QtCore.QRect(600, 200, 141, 50))
            self.lastname_error.setStyleSheet("color: rgb(255, 0, 0)")
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt; font-weight:600; color:#132d90;\">Registration of Patient</span></p></body></html>"))
        self.textEdit_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">CPR-number<span style=\" color:#fb0008; vertical-align:super;\">*</span></p></body></html>"))
        self.textEdit_3.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Date of positive pregnancy test<span style=\" color:#fc0a07; vertical-align:super;\">*</span></p></body></html>"))
        self.textEdit_4.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Weight<span style=\" color:#fb0006; vertical-align:super;\">*</span></p></body></html>"))
        self.cpr.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.Weight.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.textEdit_7.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Partner<span style=\" color:#fb0008; vertical-align:super;\">*</span></p></body></html>"))
        self.Partner.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "Register new patient"))
        self.textEdit_11.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Last name<span style=\" color:#fb0008; vertical-align:super;\">*</span></p></body></html>"))
        self.textEdit_12.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">First name<span style=\" color:#fb0008; vertical-align:super;\">*</span></p></body></html>"))
        self.Last_name.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.First_name.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.cpr_error.setHtml(_translate("MainWindow","<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">*The entered CPR-number is invalid*<span style=\" color:#fb0006; vertical-align:super;\"></span></p></body></html>"))
        self.partner_error.setHtml(_translate("MainWindow","<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">*Response shold be either 'Yes' or 'No'*<span style=\" color:#fb0006; vertical-align:super;\"></span></p></body></html>"))
        self.weight_error.setHtml(_translate("MainWindow","<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">*Weight is not between 30 and 200 kilograms*<span style*=\" color:#fb0006; vertical-align:super;\"></span></p></body></html>"))
        self.firstname_error.setHtml(_translate("MainWindow","<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">*First name must be letters*<span style*=\" color:#fb0006; vertical-align:super;\"></span></p></body></html>"))
        self.lastname_error.setHtml(_translate("MainWindow","<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">*Last name must be letters*<span style*=\" color:#fb0006; vertical-align:super;\"></span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_RegisterWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
